CREATE TABLE IF NOT EXISTS TB_USER_DEPARTMENT (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    assignment_date_time TIMESTAMP NOT NULL,
    comments VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES TB_USER(id),
    FOREIGN KEY (department_id) REFERENCES TB_DEPARTMENT(id)
)