CREATE TABLE IF NOT EXISTS TB_USER (
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    birthday_date DATE,
    admission_date DATE NOT NULL,
    contact_number VARCHAR(9) NOT NULL,
    email VARCHAR(50),
    is_active BIT NOT NULL,
    is_available_for_vacation BIT NOT NULL,
    nif VARCHAR(9) NOT NULL,
    password VARCHAR(30),
    recruitment_company VARCHAR(20) NOT NULL,
    registry_date VARCHAR(19) NOT NULL,
    updated_at VARCHAR(18),
    user_already_on_department BIT NOT NULL,
    user_role VARCHAR(15) NOT NULL,
    work_number INTEGER NOT NULL,
    work_status VARCHAR(20) NOT NULL
);