CREATE TABLE IF NOT EXISTS TB_HISTORY (
    id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(150) NOT NULL,
    action_date_time DATE NOT NULL,
    username VARCHAR(20) NOT NULL,
    entity VARCHAR(20) NOT NULL
)